server:
  port: 8000

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      mvc:
        routes:
          - id: order-service
            uri: lb://order-service # 또는 lb://order-service (Eureka 사용 시)
            predicates:
              - Path=/order/**           # 요청 매핑
              # /order 제거하고 전달 (/order/api → /api)
            filters:
              - StripPrefix=1
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

# actuator 열어두면 health 체크 편리
management:
  endpoints:
    web:
      exposure:
        include: "*"


logging:
  level:
    org.springframework.cloud.gateway: DEBUG