spring:
  application:
    name: order-service

  config:
    import: "optional:configserver:"

  cloud:
    config:
      uri: http://localhost:8888  # Config Server URL
      profile: default            # default는 생략 가능

# 필요 시 actuator 설정
management:
  endpoints:
    web:
      exposure:
        include: refresh