spring:
  application:
    name: order-service

  config:
    import: "optional:configserver:"

  cloud:
    config:
      fail-fast: false
      retry:
        max-attempts: 6
        initial-interval: 1000
      uri: http://localhost:8888  # Config Server URL
      profile: default            # default는 생략 가능
  datasource:
    url: jdbc:h2:./order-service/db_dev;MODE=MySQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
    hikari:
      auto-commit: false

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 100


# 필요 시 actuator 설정
management:
  endpoints:
    web:
      exposure:
        include: refresh